"""Optional PySide6 imports kept at the presentation boundary."""

from __future__ import annotations

try:
    from PySide6.QtCore import (
        QEasingCurve,
        QEvent,
        QObject,
        QParallelAnimationGroup,
        QPointF,
        QPropertyAnimation,
        QRect,
        QRectF,
        QRunnable,
        QSettings,
        Qt,
        QThreadPool,
        QTimer,
        Signal,
        Slot,
    )
    from PySide6.QtGui import (
        QColor,
        QFont,
        QFontDatabase,
        QIcon,
        QKeySequence,
        QPainter,
        QPen,
        QPixmap,
        QShortcut,
    )
    from PySide6.QtWidgets import (
        QApplication,
        QCheckBox,
        QComboBox,
        QDialog,
        QDoubleSpinBox,
        QFileDialog,
        QFrame,
        QGraphicsOpacityEffect,
        QGridLayout,
        QHBoxLayout,
        QHeaderView,
        QInputDialog,
        QLabel,
        QLayout,
        QLineEdit,
        QMainWindow,
        QMenu,
        QMessageBox,
        QPlainTextEdit,
        QPushButton,
        QScrollArea,
        QSizePolicy,
        QSpinBox,
        QTabBar,
        QTableWidget,
        QTableWidgetItem,
        QTabWidget,
        QToolButton,
        QVBoxLayout,
        QWidget,
    )
except ImportError as exc:
    from ..domain.errors import TransportDependencyError

    raise TransportDependencyError(
        "桌面界面需要安装 PySide6。",
        detail=str(exc),
    ) from exc


__all__ = [
    "QApplication",
    "QCheckBox",
    "QColor",
    "QComboBox",
    "QDialog",
    "QDoubleSpinBox",
    "QEasingCurve",
    "QEvent",
    "QFileDialog",
    "QFont",
    "QFontDatabase",
    "QFrame",
    "QGraphicsOpacityEffect",
    "QGridLayout",
    "QHBoxLayout",
    "QHeaderView",
    "QIcon",
    "QInputDialog",
    "QKeySequence",
    "QLabel",
    "QLayout",
    "QLineEdit",
    "QMainWindow",
    "QMenu",
    "QMessageBox",
    "QObject",
    "QPainter",
    "QParallelAnimationGroup",
    "QPen",
    "QPixmap",
    "QPlainTextEdit",
    "QPointF",
    "QPropertyAnimation",
    "QPushButton",
    "QRect",
    "QRectF",
    "QRunnable",
    "QScrollArea",
    "QSettings",
    "QShortcut",
    "QSizePolicy",
    "QSpinBox",
    "QTabBar",
    "QTabWidget",
    "QTableWidget",
    "QTableWidgetItem",
    "QThreadPool",
    "QTimer",
    "QToolButton",
    "QVBoxLayout",
    "QWidget",
    "Qt",
    "Signal",
    "Slot",
]
