/**
 * @file MemoryHexEditorExport.cpp
 * @brief 十六进制内存编辑器 — 搜索与导出方法
 * @author EmbedDebug Team
 * @date 2026-06-05
 *
 * 从MemoryHexEditor.cpp拆分: findNext/findPrev/exportToBin/exportToHex/exportToCpp
 */

#include "utils/hex_editor/MemoryHexEditor.h"

#include <QFile>
#include <QTextStream>
#include <QtMath>

// ============================================================
// 搜索
// ============================================================

int MemoryHexEditor::findNext(const QByteArray& pattern, int fromOffset)
{
    if (pattern.isEmpty() || m_data.isEmpty()) return -1;
    m_stats.totalSearches++;

    int idx = m_data.indexOf(pattern, fromOffset);
    if (idx >= 0) {
        m_selection = {idx, static_cast<int>(idx + pattern.size() - 1)};
        m_cursorPos = idx;
        ensureCursorVisible();
        emit searchFound(idx);
        emit selectionChanged(m_selection.startOffset, m_selection.endOffset);
    }
    update();
    return idx;
}

int MemoryHexEditor::findPrev(const QByteArray& pattern, int fromOffset)
{
    if (pattern.isEmpty() || m_data.isEmpty()) return -1;
    m_stats.totalSearches++;

    if (fromOffset < 0) fromOffset = m_data.size() - 1;
    int idx = m_data.lastIndexOf(pattern, fromOffset);
    if (idx >= 0) {
        m_selection = {idx, static_cast<int>(idx + pattern.size() - 1)};
        m_cursorPos = idx;
        ensureCursorVisible();
        emit searchFound(idx);
        emit selectionChanged(m_selection.startOffset, m_selection.endOffset);
    }
    update();
    return idx;
}

// ============================================================
// 导出
// ============================================================

bool MemoryHexEditor::exportToBin(const QString& filePath)
{
    QFile f(filePath);
    if (!f.open(QIODevice::WriteOnly)) return false;
    f.write(m_data);
    f.close();
    m_stats.totalExports++;
    return true;
}

bool MemoryHexEditor::exportToHex(const QString& filePath)
{
    /* Intel HEX 格式导出: 每行最多16字节的数据记录 + EOF */
    QFile f(filePath);
    if (!f.open(QIODevice::WriteOnly | QIODevice::Text)) return false;
    QTextStream out(&f);

    int offset = 0;
    while (offset < m_data.size()) {
        int chunk = qMin(16, m_data.size() - offset);
        quint8 len = static_cast<quint8>(chunk);
        quint16 addr = static_cast<quint16>(offset & 0xFFFF);
        quint8 type = 0x00; // 数据记录

        quint8 checksum = len + (addr >> 8) + (addr & 0xFF) + type;
        out << ":";
        out << QString("%1").arg(len, 2, 16, QChar('0')).toUpper();
        out << QString("%1").arg(addr, 4, 16, QChar('0')).toUpper();
        out << QString("%1").arg(type, 2, 16, QChar('0')).toUpper();

        for (int i = 0; i < chunk; ++i) {
            quint8 b = static_cast<quint8>(m_data[offset + i]);
            checksum += b;
            out << QString("%1").arg(b, 2, 16, QChar('0')).toUpper();
        }
        checksum = (~checksum + 1) & 0xFF;
        out << QString("%1").arg(checksum, 2, 16, QChar('0')).toUpper();
        out << "\n";
        offset += chunk;
    }

    /* EOF记录 */
    out << ":00000001FF\n";
    f.close();
    m_stats.totalExports++;
    return true;
}

bool MemoryHexEditor::exportToCpp(const QString& filePath)
{
    QFile f(filePath);
    if (!f.open(QIODevice::WriteOnly | QIODevice::Text)) return false;
    QTextStream out(&f);

    out << "/* Auto-generated by EmbedDebug MemoryHexEditor */\n";
    out << "#include <stdint.h>\n";
    out << "#include <stddef.h>\n\n";
    out << "const uint8_t data[" << m_data.size() << "] = {\n";

    for (int i = 0; i < m_data.size(); ++i) {
        if (i % m_bytesPerLine == 0) out << "    ";
        out << "0x" << QString("%1").arg(static_cast<uint8_t>(m_data[i]), 2, 16, QChar('0')).toUpper();
        if (i < m_data.size() - 1) out << ", ";
        if ((i + 1) % m_bytesPerLine == 0 || i == m_data.size() - 1) out << "\n";
    }

    out << "};\n";
    out << "const size_t data_size = " << m_data.size() << ";\n";
    f.close();
    m_stats.totalExports++;
    return true;
}
