@echo off
setlocal EnableExtensions EnableDelayedExpansion

set "ROOT_DIR=%~dp0"
set "ENV_FILE=%ROOT_DIR%..\local_env.bat"

echo ===========================================
echo EmbedDebug - Dev Env bootstrap
set "DATE_TIME=%DATE% %TIME%"
echo ===========================================

echo [1/4] Resolve Qt path (windeployqt)
set "QT_PREFIX="
if defined QT_PREFIX if not exist "%QT_PREFIX%\bin\windeployqt.exe" set "QT_PREFIX="
if not defined QT_PREFIX (
    where windeployqt >nul 2>&1
    if not errorlevel 1 (
        for /f "delims=" %%F in ('where windeployqt 2^>nul') do (
            set "QT_BIN_DIR=%%~dpF"
            for /f "delims=" %%Q in ("!QT_BIN_DIR!..\\") do set "QT_PREFIX=%%~fQ"
            if exist "!QT_PREFIX!\bin\windeployqt.exe" goto :qt_done
        )
    )
)
:qt_done
if defined QT_PREFIX (
    echo [OK] Qt: %QT_PREFIX%
)


echo [2/4] Resolve MinGW toolchain (gcc)
if defined MINGW_BIN if not exist "%MINGW_BIN%\gcc.exe" set "MINGW_BIN="
if not defined MINGW_BIN (
    where gcc >nul 2>&1
    if not errorlevel 1 (
        for /f "delims=" %%F in ('where gcc 2^>nul') do (
            set "MINGW_BIN=%%~dpF"
            set "MINGW_BIN=!MINGW_BIN:~0,-1!"
            goto :gcc_done
        )
    )
)
:gcc_done
if defined MINGW_BIN (
    echo [OK] GCC: %MINGW_BIN%\gcc.exe
)


echo [3/4] Check CMake and Ninja
set "CMAKE_BIN="
set "NINJA_BIN="
where cmake >nul 2>&1
if not errorlevel 1 (
    for /f "delims=" %%F in ('where cmake 2^>nul') do (
        set "CMAKE_BIN=%%~fF"
        goto :cmake_done
    )
)
:cmake_done
if defined CMAKE_BIN (
    echo [OK] CMake: %CMAKE_BIN%
)

where ninja >nul 2>&1
if not errorlevel 1 (
    for /f "delims=" %%F in ('where ninja 2^>nul') do (
        set "NINJA_BIN=%%~fF"
        goto :ninja_done
    )
)
:ninja_done
if defined NINJA_BIN (
    echo [OK] Ninja: %NINJA_BIN%
)


echo [4/4] Write local_env.bat for next launches
(
  echo @echo off
  echo rem Auto-generated by bootstrap_env.bat on %DATE_TIME%
  if defined QT_PREFIX echo set "QT_PREFIX=%QT_PREFIX%"
  if defined MINGW_BIN echo set "MINGW_BIN=%MINGW_BIN%"
  if defined CMAKE_BIN echo set "CMAKE_BIN=%CMAKE_BIN%"
  if defined NINJA_BIN echo set "NINJA_BIN=%NINJA_BIN%"
  echo.
) > "%ENV_FILE%"

if exist "%ENV_FILE%" (
    echo [OK] local_env saved: %ENV_FILE%
)

echo.
echo -------- ???? --------
if defined QT_PREFIX echo QT_PREFIX=%QT_PREFIX%
if defined MINGW_BIN echo MINGW_BIN=%MINGW_BIN%
if defined CMAKE_BIN echo CMAKE_BIN=%CMAKE_BIN%
if defined NINJA_BIN echo NINJA_BIN=%NINJA_BIN%

echo.
if defined QT_PREFIX if defined MINGW_BIN if defined CMAKE_BIN if defined NINJA_BIN (
    echo [PASS] Dependency check done. You can run EmbedDebug.bat directly.
) else (
    echo [WARN] Some dependencies are still missing, please install them and rerun.
)

echo.
pause
exit /b 0
