@echo off
setlocal EnableExtensions EnableDelayedExpansion

set "SCRIPT_DIR=%~dp0"
set "ENV_FILE=%SCRIPT_DIR%..\local_env.bat"

set "QT_PREFIX="
set "MINGW_BIN="
set "CMAKE_BIN="
set "NINJA_BIN="
set "HAS_CORE=1"

echo ==========================================
echo EmbedDebug - Dev Env bootstrap
echo Root : %SCRIPT_DIR%
echo ==========================================

if exist "%ENV_FILE%" (
    call "%ENV_FILE%"
)

call :validate_env

if not defined QT_PREFIX call :resolve_qt
if not defined MINGW_BIN call :resolve_mingw
if not defined CMAKE_BIN call :resolve_cmake
if not defined NINJA_BIN call :resolve_ninja

if not defined QT_PREFIX (
    echo [ERROR] Qt SDK not detected - windeployqt not found.
    set "HAS_CORE=0"
)
if not defined MINGW_BIN (
    echo [ERROR] MinGW/bin not detected - gcc not found.
    set "HAS_CORE=0"
)
if not defined CMAKE_BIN (
    echo [ERROR] CMake not detected.
    set "HAS_CORE=0"
)
if not defined NINJA_BIN (
    echo [ERROR] Ninja not detected.
    set "HAS_CORE=0"
)

echo.
if exist "%ENV_FILE%" del /f /q "%ENV_FILE%" >nul 2>&1
echo @echo off > "%ENV_FILE%"
echo rem Auto-generated by tools\bootstrap_env.bat >> "%ENV_FILE%"
if defined QT_PREFIX echo set "QT_PREFIX=%QT_PREFIX%" >> "%ENV_FILE%"
if defined MINGW_BIN echo set "MINGW_BIN=%MINGW_BIN%" >> "%ENV_FILE%"
if defined CMAKE_BIN echo set "CMAKE_BIN=%CMAKE_BIN%" >> "%ENV_FILE%"
if defined NINJA_BIN echo set "NINJA_BIN=%NINJA_BIN%" >> "%ENV_FILE%"
if defined CMAKE_PREFIX_PATH echo set "CMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH%" >> "%ENV_FILE%"

if exist "%ENV_FILE%" (
    echo [OK] local_env saved: %ENV_FILE%
)

echo.
if defined QT_PREFIX echo [OK] QT_PREFIX=%QT_PREFIX%
if defined MINGW_BIN echo [OK] MINGW_BIN=%MINGW_BIN%
if defined CMAKE_BIN echo [OK] CMAKE_BIN=%CMAKE_BIN%
if defined NINJA_BIN echo [OK] NINJA_BIN=%NINJA_BIN%
if defined CMAKE_PREFIX_PATH echo [OK] CMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH%

if "%HAS_CORE%"=="1" (
    echo [PASS] Dependency check done. You can run EmbedDebug.bat directly.
    echo [PASS] Tip: double-click EmbedDebug.bat after this file is generated.
) else (
    echo [WARN] Some dependencies are missing.
    echo [WARN] Re-run after installing missing tools and re-run this bootstrap.
    echo [WARN] You can still keep local_env.bat and adjust it manually if you know exact paths.
)

echo.
echo [STEP] Install suggestions:
echo   1. Install Qt 6.x with MinGW kit - windeployqt.exe should exist.
echo   2. Install CMake and Ninja, or add existing tools to PATH.
echo   3. Install MinGW toolchain and add gcc/g++ to PATH or set MINGW_BIN manually.
echo   4. Re-run tools\bootstrap_env.bat, then double-click EmbedDebug.bat.
echo.
pause
if "%HAS_CORE%"=="1" exit /b 0
exit /b 1

:validate_env
if defined QT_PREFIX (
    if not exist "%QT_PREFIX%\bin\windeployqt.exe" set "QT_PREFIX="
)
if defined MINGW_BIN if not exist "%MINGW_BIN%\gcc.exe" set "MINGW_BIN="
if defined CMAKE_BIN if not exist "%CMAKE_BIN%" set "CMAKE_BIN="
if defined NINJA_BIN if not exist "%NINJA_BIN%" set "NINJA_BIN="
exit /b 0

:resolve_qt
if defined QTPATH set "CMAKE_PREFIX_PATH=%QTPATH%"
if defined CMAKE_PREFIX_PATH (
    for /f "tokens=1 delims=;" %%P in ("%CMAKE_PREFIX_PATH%") do (
        if exist "%%~P\bin\windeployqt.exe" (
            set "QT_PREFIX=%%~P"
            exit /b 0
        )
    )
)

if defined QTDIR (
    if exist "%QTDIR%\bin\windeployqt.exe" (
        set "QT_PREFIX=%QTDIR%"
        exit /b 0
    )
)
if defined QT_DIR (
    if exist "%QT_DIR%\bin\windeployqt.exe" (
        set "QT_PREFIX=%QT_DIR%"
        exit /b 0
    )
)

for %%R in ("%ProgramFiles%\Qt" "%ProgramFiles(x86)%\Qt" "C:\Qt" "D:\Qt" "E:\Tool\DevEnv\Qt") do (
    if exist "%%~R" (
        call :scan_qt_root "%%~R"
        if defined QT_PREFIX exit /b 0
    )
)

where windeployqt >nul 2>&1
if errorlevel 0 (
    for /f "delims=" %%F in ('where windeployqt 2^>nul') do (
        call :resolve_qt_from_file "%%~dpF"
        if defined QT_PREFIX exit /b 0
    )
)

exit /b 0

:resolve_qt_from_file
set "QT_FILE_DIR=%~1"
set "QT_PREFIX="

if exist "%QT_FILE_DIR%\bin\windeployqt.exe" (
    for %%R in ("%QT_FILE_DIR%\..") do set "QT_PREFIX=%%~fR"
)
if exist "%QT_FILE_DIR%\windeployqt.exe" (
    for %%R in ("%QT_FILE_DIR%\..") do set "QT_PREFIX=%%~fR"
)

if defined QT_PREFIX (
    if exist "%QT_PREFIX%\bin\windeployqt.exe" exit /b 0
)
set "QT_PREFIX="
exit /b 0

:scan_qt_root
if not exist "%~1" exit /b 0
if exist "%~1\bin\windeployqt.exe" (
    set "QT_PREFIX=%~1"
    exit /b 0
)
for /d %%V in ("%~1\*") do (
    if exist "%%~fV\bin\windeployqt.exe" (
        set "QT_PREFIX=%%~fV"
        exit /b 0
    )
    for /d %%W in ("%%~fV\*") do (
        if exist "%%~fW\bin\windeployqt.exe" (
            set "QT_PREFIX=%%~fW"
            exit /b 0
        )
    )
)
exit /b 0

:resolve_mingw
where gcc >nul 2>&1
if not errorlevel 1 (
    for /f "delims=" %%F in ('where gcc 2^>nul') do (
        for %%R in ("%%~dpF.") do set "MINGW_BIN=%%~fR"
        if exist "%MINGW_BIN%\gcc.exe" (
            echo [OK] resolve MINGW_BIN=%MINGW_BIN%
            exit /b 0
        )
    )
)

for %%R in (
    "C:\mingw64\bin"
    "C:\mingw\bin"
    "C:\Program Files\mingw64\bin"
    "C:\Program Files (x86)\mingw-w64\mingw64\bin"
    "E:\Tool\DevEnv\x86_64-14.2.0-release-win32-seh-msvcrt-rt_v12-rev2\mingw64\bin"
) do (
    if exist "%%~R\gcc.exe" (
        set "MINGW_BIN=%%~R"
        echo [OK] resolve MINGW_BIN=%%~R
        exit /b 0
    )
)
exit /b 0

:resolve_cmake
if defined CMAKE_BIN if not exist "%CMAKE_BIN%" set "CMAKE_BIN="
if defined CMAKE_BIN exit /b 0
where cmake >nul 2>&1
if not errorlevel 1 (
    for /f "delims=" %%F in ('where cmake 2^>nul') do (
        set "CMAKE_BIN=%%~fF"
        echo [OK] resolve CMAKE_BIN=%CMAKE_BIN%
        exit /b 0
    )
)
for %%R in (
    "%ProgramFiles%\\CMake\\bin\\cmake.exe"
    "%ProgramFiles(x86)%\\CMake\\bin\\cmake.exe"
) do (
    if exist "%%~R" (
        set "CMAKE_BIN=%%~R"
        echo [OK] resolve CMAKE_BIN=%%~R
        exit /b 0
    )
)
exit /b 0

:resolve_ninja
if defined NINJA_BIN if not exist "%NINJA_BIN%" set "NINJA_BIN="
if defined NINJA_BIN exit /b 0
where ninja >nul 2>&1
if not errorlevel 1 (
    for /f "delims=" %%F in ('where ninja 2^>nul') do (
        set "NINJA_BIN=%%~fF"
        echo [OK] resolve NINJA_BIN=%NINJA_BIN%
        exit /b 0
    )
)
for %%R in (
    "%LOCALAPPDATA%\\Microsoft\\WinGet\\Packages\\Ninja-build.Ninja_Microsoft.Winget.Source_8wekyb3d8bbwe\\ninja.exe"
    "%ProgramFiles%\\ninja\\ninja.exe"
    "C:\ninja\ninja.exe"
) do (
    if exist "%%~R" (
        set "NINJA_BIN=%%~R"
        echo [OK] resolve NINJA_BIN=%%~R
        exit /b 0
    )
)
exit /b 0
