param(
    [Parameter(Mandatory = $true)]
    [string]$RootDir,

    [string]$AppArguments = ""
)

$ErrorActionPreference = "Stop"

function Write-Info([string]$Message) { Write-Host "[INFO] $Message" }
function Write-Ok([string]$Message) { Write-Host "[OK] $Message" }
function Write-Warn([string]$Message) { Write-Host "[WARN] $Message" }
function Write-Fail([string]$Message) { Write-Host "[ERROR] $Message" }

function Resolve-CommandPath([string]$Name) {
    $cmd = Get-Command $Name -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($cmd) { return $cmd.Source }
    return $null
}

function Test-Exe([string]$Path) {
    return -not [string]::IsNullOrWhiteSpace($Path) -and (Test-Path -LiteralPath $Path -PathType Leaf)
}

function Read-LocalEnv([string]$EnvFile) {
    $result = @{}
    if (-not (Test-Path -LiteralPath $EnvFile -PathType Leaf)) {
        return $result
    }

    foreach ($line in Get-Content -LiteralPath $EnvFile) {
        if ($line -match '^\s*set\s+"([^=]+)=(.*)"\s*$') {
            $result[$matches[1]] = $matches[2]
        }
    }
    return $result
}

function Write-LocalEnv([string]$EnvFile, [hashtable]$Env) {
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("@echo off")
    $lines.Add("rem Auto-generated by tools\launch_embeddebug.ps1")
    foreach ($name in @("QT_PREFIX", "MINGW_BIN", "CMAKE_BIN", "NINJA_BIN", "CMAKE_PREFIX_PATH")) {
        if ($Env.ContainsKey($name) -and -not [string]::IsNullOrWhiteSpace($Env[$name])) {
            $lines.Add(("set ""{0}={1}""" -f $name, $Env[$name]))
        }
    }
    Set-Content -LiteralPath $EnvFile -Value $lines -Encoding ASCII
}

function Find-QtPrefix([hashtable]$Env, [string]$RootDir) {
    $candidates = New-Object System.Collections.Generic.List[string]

    foreach ($key in @("QT_PREFIX", "CMAKE_PREFIX_PATH")) {
        if ($Env.ContainsKey($key)) {
            foreach ($part in ($Env[$key] -split ";")) {
                if (-not [string]::IsNullOrWhiteSpace($part)) { $candidates.Add($part) }
            }
        }
    }

    foreach ($name in @("QTDIR", "QT_DIR", "CMAKE_PREFIX_PATH")) {
        $value = [Environment]::GetEnvironmentVariable($name)
        if (-not [string]::IsNullOrWhiteSpace($value)) {
            foreach ($part in ($value -split ";")) {
                if (-not [string]::IsNullOrWhiteSpace($part)) { $candidates.Add($part) }
            }
        }
    }

    $windeploy = Resolve-CommandPath "windeployqt.exe"
    if ($windeploy) {
        $bin = Split-Path -Parent $windeploy
        $candidates.Add((Split-Path -Parent $bin))
    }

    foreach ($root in @(
        "C:\msys64\mingw64",
        (Join-Path $RootDir "third_party\Qt"),
        "$env:ProgramFiles\Qt",
        "${env:ProgramFiles(x86)}\Qt",
        "C:\Qt",
        "D:\Qt",
        "E:\Tool\DevEnv\Qt"
    )) {
        if (Test-Path -LiteralPath $root -PathType Container) {
            $matches = Get-ChildItem -LiteralPath $root -Recurse -Filter windeployqt.exe -ErrorAction SilentlyContinue |
                Select-Object -First 20
            foreach ($item in $matches) {
                $candidates.Add((Split-Path -Parent (Split-Path -Parent $item.FullName)))
            }
        }
    }

    foreach ($candidate in $candidates) {
        if ([string]::IsNullOrWhiteSpace($candidate)) { continue }
        $full = [System.IO.Path]::GetFullPath($candidate)
        if (Test-Exe (Join-Path $full "bin\windeployqt.exe")) {
            return $full
        }
    }
    return $null
}

function Find-MinGwBin([hashtable]$Env, [string]$RootDir) {
    $candidates = New-Object System.Collections.Generic.List[string]
    if ($Env.ContainsKey("MINGW_BIN")) { $candidates.Add($Env["MINGW_BIN"]) }

    $gcc = Resolve-CommandPath "gcc.exe"
    if ($gcc) { $candidates.Add((Split-Path -Parent $gcc)) }

    foreach ($path in @(
        "C:\msys64\mingw64\bin",
        (Join-Path $RootDir "third_party\mingw64\bin"),
        "C:\mingw64\bin",
        "C:\mingw\bin",
        "$env:ProgramFiles\mingw64\bin",
        "${env:ProgramFiles(x86)}\mingw-w64\mingw64\bin",
        "E:\Tool\DevEnv\x86_64-14.2.0-release-win32-seh-msvcrt-rt_v12-rev2\mingw64\bin"
    )) {
        $candidates.Add($path)
    }

    foreach ($candidate in $candidates) {
        if ([string]::IsNullOrWhiteSpace($candidate)) { continue }
        if (-not (Test-Path -LiteralPath $candidate -PathType Container)) { continue }
        if ((Test-Exe ([System.IO.Path]::Combine($candidate, "gcc.exe"))) -and (Test-Exe ([System.IO.Path]::Combine($candidate, "g++.exe")))) {
            return [System.IO.Path]::GetFullPath($candidate)
        }
    }
    return $null
}

function Resolve-Toolchain([string]$RootDir) {
    $envFile = Join-Path $RootDir "local_env.bat"
    $envMap = Read-LocalEnv $envFile

    if (-not $envMap.ContainsKey("CMAKE_BIN") -or -not (Test-Exe $envMap["CMAKE_BIN"])) {
        $cmake = Resolve-CommandPath "cmake.exe"
        if ($cmake) { $envMap["CMAKE_BIN"] = $cmake }
    }
    if (-not $envMap.ContainsKey("NINJA_BIN") -or -not (Test-Exe $envMap["NINJA_BIN"])) {
        $ninja = Resolve-CommandPath "ninja.exe"
        if ($ninja) { $envMap["NINJA_BIN"] = $ninja }
    }

    $qt = Find-QtPrefix $envMap $RootDir
    if ($qt) {
        $envMap["QT_PREFIX"] = $qt
        $envMap["CMAKE_PREFIX_PATH"] = $qt
    }

    $mingw = Find-MinGwBin $envMap $RootDir
    if ($mingw) { $envMap["MINGW_BIN"] = $mingw }

    Write-LocalEnv $envFile $envMap
    return $envMap
}

function Assert-Toolchain([hashtable]$Env) {
    $missing = New-Object System.Collections.Generic.List[string]
    if (-not $Env.ContainsKey("QT_PREFIX") -or -not (Test-Exe (Join-Path $Env["QT_PREFIX"] "bin\windeployqt.exe"))) {
        $missing.Add("Qt MinGW SDK with windeployqt.exe")
    }
    if (-not $Env.ContainsKey("MINGW_BIN") -or -not (Test-Exe (Join-Path $Env["MINGW_BIN"] "g++.exe"))) {
        $missing.Add("MinGW desktop compiler with gcc.exe and g++.exe")
    }
    if (-not $Env.ContainsKey("CMAKE_BIN") -or -not (Test-Exe $Env["CMAKE_BIN"])) {
        $missing.Add("CMake")
    }
    if (-not $Env.ContainsKey("NINJA_BIN") -or -not (Test-Exe $Env["NINJA_BIN"])) {
        $missing.Add("Ninja")
    }

    if ($missing.Count -gt 0) {
        Write-Fail "Required build/runtime dependencies are missing:"
        foreach ($item in $missing) { Write-Host "  - $item" }
        Write-Host ""
        Write-Host "Install path expected by project constraints:"
        Write-Host "  Qt:    E:\Tool\DevEnv\Qt\6.8.3\mingw_64"
        Write-Host "  MinGW: E:\Tool\DevEnv\x86_64-14.2.0-release-win32-seh-msvcrt-rt_v12-rev2\mingw64\bin"
        Write-Host ""
        Write-Host "After installing, double-click EmbedDebug.bat again."
        exit 2
    }
}

$root = [System.IO.Path]::GetFullPath($RootDir)
$buildDir = Join-Path $root "build"
$exePath = Join-Path $buildDir "EmbedDebug.exe"

Write-Host "-------------------------------------------------"
Write-Host "EmbedDebug Launcher"
Write-Host "Root : $root"
Write-Host "-------------------------------------------------"

$toolchain = Resolve-Toolchain $root
Assert-Toolchain $toolchain

$qtToolBin = Join-Path $toolchain["QT_PREFIX"] "share\qt6\bin"
$env:PATH = "$qtToolBin;$($toolchain["QT_PREFIX"])\bin;$($toolchain["MINGW_BIN"]);$env:PATH"
$env:QT_PLUGIN_PATH = Join-Path $toolchain["QT_PREFIX"] "plugins"
$env:QML2_IMPORT_PATH = Join-Path $toolchain["QT_PREFIX"] "qml"

Write-Info "toolchain:"
Write-Host "  CMAKE_BIN=$($toolchain["CMAKE_BIN"])"
Write-Host "  NINJA_BIN=$($toolchain["NINJA_BIN"])"
Write-Host "  MINGW_BIN=$($toolchain["MINGW_BIN"])"
Write-Host "  QT_PREFIX=$($toolchain["QT_PREFIX"])"

if (-not (Test-Path -LiteralPath $buildDir -PathType Container)) {
    Write-Info "create build directory: $buildDir"
    New-Item -ItemType Directory -Path $buildDir | Out-Null
}

if (-not (Test-Exe $exePath)) {
    $cachePath = Join-Path $buildDir "CMakeCache.txt"
    if (Test-Path -LiteralPath $cachePath -PathType Leaf) {
        $cacheText = Get-Content -LiteralPath $cachePath -Raw
        if ($cacheText -match "CMAKE_CXX_COMPILER-NOTFOUND" -or $cacheText -match [regex]::Escape("E:/Tool/DevEnv/Qt/6.8.3/mingw_64")) {
            Write-Warn "stale CMake cache detected, removing cache files inside build."
            Remove-Item -LiteralPath $cachePath -Force
            $cmakeFiles = Join-Path $buildDir "CMakeFiles"
            if (Test-Path -LiteralPath $cmakeFiles -PathType Container) {
                Remove-Item -LiteralPath $cmakeFiles -Recurse -Force
            }
        }
    }

    Write-Info "EmbedDebug.exe not found, configure and build now."
    & $toolchain["CMAKE_BIN"] -S $root -B $buildDir -G Ninja -DCMAKE_BUILD_TYPE=Release "-DCMAKE_PREFIX_PATH=$($toolchain["QT_PREFIX"])" "-DCMAKE_MAKE_PROGRAM=$($toolchain["NINJA_BIN"])" "-DCMAKE_C_COMPILER=$($toolchain["MINGW_BIN"])\gcc.exe" "-DCMAKE_CXX_COMPILER=$($toolchain["MINGW_BIN"])\g++.exe"
    if ($LASTEXITCODE -ne 0) { throw "CMake configure failed with exit code $LASTEXITCODE." }

    & $toolchain["CMAKE_BIN"] --build $buildDir --config Release
    if ($LASTEXITCODE -ne 0) { throw "Build failed with exit code $LASTEXITCODE." }
}

if (-not (Test-Exe $exePath)) {
    throw "Build finished but EmbedDebug.exe was not found in build."
}

$windeploy = Join-Path $toolchain["QT_PREFIX"] "bin\windeployqt.exe"
if (-not (Test-Path -LiteralPath (Join-Path $buildDir "Qt6Core.dll") -PathType Leaf)) {
    Write-Info "deploy Qt runtime with windeployqt."
    & $windeploy $exePath
    if ($LASTEXITCODE -ne 0) { Write-Warn "windeployqt returned exit code $LASTEXITCODE, launch will still be attempted." }
}

Write-Info "start EmbedDebug."
$startProcessArgs = @{
    FilePath = $exePath
    WorkingDirectory = $buildDir
    PassThru = $true
}
if (-not [string]::IsNullOrWhiteSpace($AppArguments)) {
    Write-Info "application arguments: $AppArguments"
    $startProcessArgs["ArgumentList"] = $AppArguments
}
$process = Start-Process @startProcessArgs
Start-Sleep -Seconds 1

if ($process.HasExited) {
    throw "EmbedDebug exited immediately with code $($process.ExitCode). Check Qt runtime DLLs and application startup code."
}

Write-Ok "EmbedDebug process started. PID=$($process.Id)"
exit 0
