@echo off
rem Auto-generated by bootstrap_env.bat on 周五 2026/06/12  1:49:35.66
set "CMAKE_BIN=C:\Program Files\CMake\bin\cmake.exe"
set "NINJA_BIN=C:\Users\LWH\AppData\Local\Microsoft\WinGet\Packages\Ninja-build.Ninja_Microsoft.Winget.Source_8wekyb3d8bbwe\ninja.exe"

